import "./globals.css";
import Link from 'next/link';
import { ticketsPath } from "@/app/path";
import { homePath } from "@/app/path";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { buttonVariants } from "@/components/ui/button";
import { LucideKanban } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav 
          className="
            supports-backdrop-blur:bg-secondary/60
            fixed le0 right-0 top-0 z-20
            border-b bg-white/60 backdrop-blur
            w-full flex py-2.5 px-5 justify-between"
        > 
          <div> 
            <Link href={homePath()} className={buttonVariants({ variant: "ghost"})}>
              <LucideKanban />
              <h1 className="text-lg font-semi">TicketBonus</h1>
            </Link>
          </div>
          <div> 
            <Link href={ticketsPath()} className={buttonVariants({ variant: "default"})}>
            <h1 className="text-lg font-semi">Tickets</h1>
            </Link>
          </div>
        </nav>
        <main 
          className="
            min-h-screen flex-1 
            overflow-auto overflow-hidden
            py-24 px-8
            bg-secondary/20
            flex flex-col animate-fade-in-up">
          {children}
        </main>
      </body>
    </html>
  );
}
