import "./globals.css";
import Link from 'next/link';
import { ticketsPath } from "@/app/path";
import { homePath } from "@/app/path";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { buttonVariants } from "@/components/ui/button";
import { LucideKanban } from "lucide-react";
import {Header} from "@/components/header"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main 
          className="
            min-h-screen flex-1 
            overflow-auto overflow-hidden
            py-24 px-8
            bg-secondary/20
            flex flex-col animate-fade-in-up">
          {children}
        </main>
      </body>
    </html>
  );
}
